version: "2.2"
services:
  jd-seckill:
    container_name: jd-seckill
    image: registry.cn-hangzhou.aliyuncs.com/yakun/jd_seckill:latest
    build:
      context: ../dockerfile
      dockerfile: Dockerfile
    env_file:
      - ../dockerfile/docker.env
